title: Gabriel Poça
email: gabrielpoca@gmail.com
description: "Personal technical blog."
baseurl: ""
url: "http://gabrielpoca.com"
twitter_username: gabrielgpoca
github_username:  gabrielpoca

markdown: kramdown

kramdown:
  input: GFM
  use_coderay: true
  coderay:
    coderay_line_numbers:      nil

gravatar:
  default_image: mm
  size: 600
  rating: g
  secure: true
